name: pilot_bazar_admin
description: "A new Flutter project."

publish_to: 'none' 



environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  flutter_fancy_tree_view: ^1.4.1
  flutter_simple_treeview: ^3.0.2
  arrow_path: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: AbhayaLibre
      fonts:
        - asset: fonts/AbhayaLibre-Regular.ttf  
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf    
    - family: Axiforma
      fonts:
        - asset: fonts/Axiforma-Regular.ttf  
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf  
